// packages/react/src/floating-ui-react/components/FloatingDelayGroup.tsx
import * as React from 'react';
import { useModernLayoutEffect } from '../../utils/useModernLayoutEffect';
import { Timeout, useTimeout } from '../../utils/useTimeout';

import { getDelay } from '../hooks/useHover';
import type { Delay, FloatingRootContext } from '../types';

interface ContextValue {
  hasProvider: boolean;
  timeoutMs: number;
  delayRef: React.MutableRefObject<Delay>;
  initialDelayRef: React.MutableRefObject<Delay>;
  timeout: Timeout;
  currentIdRef: React.MutableRefObject<any>;
  currentContextRef: React.MutableRefObject<{
    onOpenChange: (open: boolean) => void;
    setIsInstantPhase: (value: boolean) => void;
  } | null>;
}

const FloatingDelayGroupContext = React.createContext<ContextValue>({
  hasProvider: false,
  timeoutMs: 0,
  delayRef: { current: 0 },
  initialDelayRef: { current: 0 },
  timeout: new Timeout(),
  currentIdRef: { current: null },
  currentContextRef: { current: null },
});

export interface FloatingDelayGroupProps {
  children?: React.ReactNode;
  /**
   * The delay to use for the group when it's not in the instant phase.
   */
  delay: Delay;
  /**
   * An optional explicit timeout to use for the group, which represents when
   * grouping logic will no longer be active after the close delay completes.
   * This is useful if you want grouping to “last” longer than the close delay,
   * for example if there is no close delay at all.
   */
  timeoutMs?: number;
}

/**
 * Experimental next version of `FloatingDelayGroup` to become the default
 * in the future. This component is not yet stable.
 * Provides context for a group of floating elements that should share a
 * `delay`. Unlike `FloatingDelayGroup`, `useDelayGroup` with this
 * component does not cause a re-render of unrelated consumers of the
 * context when the delay changes.
 * @see https://floating-ui.com/docs/FloatingDelayGroup
 * @internal
 */
export function FloatingDelayGroup(props: FloatingDelayGroupProps): React.JSX.Element {
  const { children, delay, timeoutMs = 0 } = props;

  const delayRef = React.useRef(delay);
  const initialDelayRef = React.useRef(delay);
  const currentIdRef = React.useRef<string | null>(null);
  const currentContextRef = React.useRef(null);
  const timeout = useTimeout();

  return (
    <FloatingDelayGroupContext.Provider
      value={React.useMemo(
        () => ({
          hasProvider: true,
          delayRef,
          initialDelayRef,
          currentIdRef,
          timeoutMs,
          currentContextRef,
          timeout,
        }),
        [timeoutMs, timeout],
      )}
    >
      {children}
    </FloatingDelayGroupContext.Provider>
  );
}

interface UseDelayGroupOptions {
  /**
   * Whether delay grouping should be enabled.
   * @default true
   */
  enabled?: boolean;
}

interface UseDelayGroupReturn {
  /**
   * The delay reference object.
   */
  delayRef: React.MutableRefObject<Delay>;
  /**
   * Whether animations should be removed.
   */
  isInstantPhase: boolean;
  /**
   * Whether a `<FloatingDelayGroup>` provider is present.
   */
  hasProvider: boolean;
}

/**
 * Enables grouping when called inside a component that's a child of a
 * `FloatingDelayGroup`.
 * @see https://floating-ui.com/docs/FloatingDelayGroup
 * @internal
 */
export function useDelayGroup(
  context: FloatingRootContext,
  options: UseDelayGroupOptions = {},
): UseDelayGroupReturn {
  const { open, onOpenChange, floatingId } = context;
  const { enabled = true } = options;

  const groupContext = React.useContext(FloatingDelayGroupContext);
  const {
    currentIdRef,
    delayRef,
    timeoutMs,
    initialDelayRef,
    currentContextRef,
    hasProvider,
    timeout,
  } = groupContext;

  const [isInstantPhase, setIsInstantPhase] = React.useState(false);

  useModernLayoutEffect(() => {
    function unset() {
      setIsInstantPhase(false);
      currentContextRef.current?.setIsInstantPhase(false);
      currentIdRef.current = null;
      currentContextRef.current = null;
      delayRef.current = initialDelayRef.current;
    }

    if (!enabled) {
      return undefined;
    }
    if (!currentIdRef.current) {
      return undefined;
    }

    if (!open && currentIdRef.current === floatingId) {
      setIsInstantPhase(false);

      if (timeoutMs) {
        timeout.start(timeoutMs, unset);
        return () => {
          timeout.clear();
        };
      }

      unset();
    }
    return undefined;
  }, [
    enabled,
    open,
    floatingId,
    currentIdRef,
    delayRef,
    timeoutMs,
    initialDelayRef,
    currentContextRef,
    timeout,
  ]);

  useModernLayoutEffect(() => {
    if (!enabled) {
      return;
    }
    if (!open) {
      return;
    }

    const prevContext = currentContextRef.current;
    const prevId = currentIdRef.current;

    currentContextRef.current = { onOpenChange, setIsInstantPhase };
    currentIdRef.current = floatingId;
    delayRef.current = {
      open: 0,
      close: getDelay(initialDelayRef.current, 'close'),
    };

    if (prevId !== null && prevId !== floatingId) {
      timeout.clear();
      setIsInstantPhase(true);
      prevContext?.setIsInstantPhase(true);
      prevContext?.onOpenChange(false);
    } else {
      setIsInstantPhase(false);
      prevContext?.setIsInstantPhase(false);
    }
  }, [
    enabled,
    open,
    floatingId,
    onOpenChange,
    currentIdRef,
    delayRef,
    timeoutMs,
    initialDelayRef,
    currentContextRef,
    timeout,
  ]);

  useModernLayoutEffect(() => {
    return () => {
      currentContextRef.current = null;
    };
  }, [currentContextRef]);

  return React.useMemo(
    () => ({
      hasProvider,
      delayRef,
      isInstantPhase,
    }),
    [hasProvider, delayRef, isInstantPhase],
  );
}

// packages/solid/src/floating-ui-solid/components/FloatingDelayGroup.tsx
import {
  createContext,
  createEffect,
  createSignal,
  onCleanup,
  useContext,
  type Accessor,
  type JSX,
} from 'solid-js';
import { useTimeout, type Timeout } from '../../utils/useTimeout';

import { getDelay } from '../hooks/useHover';
import type { Delay, FloatingRootContext } from '../types';

interface ContextValue {
  hasProvider: Accessor<boolean>;
  setHasProvider: (value: boolean) => void;
  timeoutMs: Accessor<number>;
  setTimeoutMs: (value: number) => void;
  delayRef: Accessor<Delay>;
  setDelayRef: (value: Delay) => void;
  initialDelayRef: Delay;
  timeout: Timeout;
  currentIdRef: Accessor<any>;
  setCurrentIdRef: (value: any) => void;
  currentContextRef: {
    onOpenChange: (open: boolean) => void;
    setIsInstantPhase: (value: boolean) => void;
  } | null;
}

const FloatingDelayGroupContext = createContext<ContextValue>({
  hasProvider: () => false,
  setHasProvider: () => {},
  timeoutMs: () => 0,
  setTimeoutMs: () => {},
  delayRef: () => 0,
  setDelayRef: () => {},
  currentIdRef: () => null,
  setCurrentIdRef: () => {},
  initialDelayRef: 0,
  timeout: useTimeout(),
  currentContextRef: null,
});

export interface FloatingDelayGroupProps {
  children?: JSX.Element;
  /**
   * The delay to use for the group when it's not in the instant phase.
   */
  delay: Delay;
  /**
   * An optional explicit timeout to use for the group, which represents when
   * grouping logic will no longer be active after the close delay completes.
   * This is useful if you want grouping to “last” longer than the close delay,
   * for example if there is no close delay at all.
   */
  timeoutMs?: number;
}

/**
 * Experimental next version of `FloatingDelayGroup` to become the default
 * in the future. This component is not yet stable.
 * Provides context for a group of floating elements that should share a
 * `delay`. Unlike `FloatingDelayGroup`, `useDelayGroup` with this
 * component does not cause a re-render of unrelated consumers of the
 * context when the delay changes.
 * @see https://floating-ui.com/docs/FloatingDelayGroup
 * @internal
 */
export function FloatingDelayGroup(props: FloatingDelayGroupProps): JSX.Element {
  let initialDelayRef = props.delay;
  const [hasProvider, setHasProvider] = createSignal(false);
  const [timeoutMs, setTimeoutMs] = createSignal(props.timeoutMs ?? 0);
  const [delayRef, setDelayRef] = createSignal<Delay>(0);
  const [currentIdRef, setCurrentIdRef] = createSignal<any>(null);
  const currentContextRef: ContextValue['currentContextRef'] = null;
  const timeout = useTimeout();

  return (
    <FloatingDelayGroupContext.Provider
      value={{
        hasProvider,
        setHasProvider,
        timeoutMs,
        setTimeoutMs,
        delayRef,
        setDelayRef,
        currentIdRef,
        setCurrentIdRef,
        initialDelayRef,
        timeout,
        currentContextRef,
      }}
    >
      {props.children}
    </FloatingDelayGroupContext.Provider>
  );
}

interface UseDelayGroupOptions {
  /**
   * Whether delay grouping should be enabled.
   * @default true
   */
  enabled?: Accessor<boolean>;
}

interface UseDelayGroupReturn {
  /**
   * The delay reference object.
   */
  delayRef: Accessor<Delay>;
  /**
   * Whether animations should be removed.
   */
  isInstantPhase: Accessor<boolean>;
  /**
   * Whether a `<FloatingDelayGroup>` provider is present.
   */
  hasProvider: Accessor<boolean>;
}

/**
 * Enables grouping when called inside a component that's a child of a
 * `FloatingDelayGroup`.
 * @see https://floating-ui.com/docs/FloatingDelayGroup
 * @internal
 */
export function useDelayGroup(
  context: FloatingRootContext,
  options: UseDelayGroupOptions = {},
): UseDelayGroupReturn {
  const enabled = () => options.enabled?.() ?? true;

  const groupContext = useContext(FloatingDelayGroupContext);

  const [isInstantPhase, setIsInstantPhase] = createSignal(false);

  createEffect(() => {
    function unset() {
      setIsInstantPhase(false);
      groupContext.currentContextRef?.setIsInstantPhase(false);
      groupContext.setCurrentIdRef(null);
      groupContext.currentContextRef = null;
      groupContext.setDelayRef(groupContext.initialDelayRef);
    }

    if (!enabled()) {
      return;
    }
    if (!groupContext.currentIdRef()) {
      return;
    }

    if (!context.open() && groupContext.currentIdRef() === context.floatingId()) {
      setIsInstantPhase(false);

      if (groupContext.timeoutMs()) {
        groupContext.timeout.start(groupContext.timeoutMs(), unset);

        onCleanup(() => {
          groupContext.timeout.clear();
        });
      }

      unset();
    }
  });

  createEffect(() => {
    if (!enabled()) {
      return;
    }
    if (!context.open()) {
      return;
    }

    const prevContext = groupContext.currentContextRef;
    const prevId = groupContext.currentIdRef();

    groupContext.currentContextRef = { onOpenChange: context.onOpenChange, setIsInstantPhase };
    groupContext.setCurrentIdRef(context.floatingId());
    groupContext.setDelayRef({
      open: 0,
      close: getDelay(() => groupContext.initialDelayRef, 'close'),
    });

    if (prevId !== null && prevId !== context.floatingId()) {
      groupContext.timeout.clear();
      setIsInstantPhase(true);
      prevContext?.setIsInstantPhase(true);
      prevContext?.onOpenChange(false);
    } else {
      setIsInstantPhase(false);
      prevContext?.setIsInstantPhase(false);
    }
  });

  createEffect(() => {
    onCleanup(() => {
      groupContext.currentContextRef = null;
    });
  });

  return {
    hasProvider: groupContext.hasProvider,
    delayRef: groupContext.delayRef,
    isInstantPhase,
  };
}
