// packages/react/src/collapsible/panel/CollapsiblePanel.tsx
'use client';
import * as React from 'react';
import { BaseUIComponentProps } from '../../utils/types';
import { useModernLayoutEffect } from '../../utils/useModernLayoutEffect';
import { useOpenChangeComplete } from '../../utils/useOpenChangeComplete';
import { useRenderElement } from '../../utils/useRenderElement';
import type { TransitionStatus } from '../../utils/useTransitionStatus';
import { warn } from '../../utils/warn';
import type { CollapsibleRoot } from '../root/CollapsibleRoot';
import { useCollapsibleRootContext } from '../root/CollapsibleRootContext';
import { collapsibleStyleHookMapping } from '../root/styleHooks';
import { CollapsiblePanelCssVars } from './CollapsiblePanelCssVars';
import { useCollapsiblePanel } from './useCollapsiblePanel';

/**
 * A panel with the collapsible contents.
 * Renders a `<div>` element.
 *
 * Documentation: [Base UI Collapsible](https://base-ui.com/react/components/collapsible)
 */
export const CollapsiblePanel = React.forwardRef(function CollapsiblePanel(
  componentProps: CollapsiblePanel.Props,
  forwardedRef: React.ForwardedRef<HTMLDivElement>,
) {
  const {
    className,
    hiddenUntilFound: hiddenUntilFoundProp,
    keepMounted: keepMountedProp,
    render,
    id: idProp,
    ...elementProps
  } = componentProps;

  if (process.env.NODE_ENV !== 'production') {
    useModernLayoutEffect(() => {
      if (hiddenUntilFoundProp && keepMountedProp === false) {
        warn(
          'The `keepMounted={false}` prop on a Collapsible will be ignored when using `hiddenUntilFound` since it requires the Panel to remain mounted even when closed.',
        );
      }
    }, [hiddenUntilFoundProp, keepMountedProp]);
  }

  const {
    abortControllerRef,
    animationTypeRef,
    height,
    mounted,
    onOpenChange,
    open,
    panelId,
    panelRef,
    runOnceAnimationsFinish,
    setDimensions,
    setHiddenUntilFound,
    setKeepMounted,
    setMounted,
    setPanelIdState,
    setOpen,
    setVisible,
    state,
    transitionDimensionRef,
    visible,
    width,
    transitionStatus,
  } = useCollapsibleRootContext();

  const hiddenUntilFound = hiddenUntilFoundProp ?? false;
  const keepMounted = keepMountedProp ?? false;

  useModernLayoutEffect(() => {
    if (idProp) {
      setPanelIdState(idProp);
      return () => {
        setPanelIdState(undefined);
      };
    }
    return undefined;
  }, [idProp, setPanelIdState]);

  useModernLayoutEffect(() => {
    setHiddenUntilFound(hiddenUntilFound);
  }, [setHiddenUntilFound, hiddenUntilFound]);

  useModernLayoutEffect(() => {
    setKeepMounted(keepMounted);
  }, [setKeepMounted, keepMounted]);

  const { props } = useCollapsiblePanel({
    abortControllerRef,
    animationTypeRef,
    externalRef: forwardedRef,
    height,
    hiddenUntilFound,
    id: panelId,
    keepMounted,
    mounted,
    onOpenChange,
    open,
    panelRef,
    runOnceAnimationsFinish,
    setDimensions,
    setMounted,
    setOpen,
    setVisible,
    transitionDimensionRef,
    visible,
    width,
  });

  useOpenChangeComplete({
    open,
    ref: panelRef,
    onComplete() {
      if (!open) {
        return;
      }

      setDimensions({ height: undefined, width: undefined });
    },
  });

  const panelState: CollapsiblePanel.State = React.useMemo(
    () => ({
      ...state,
      transitionStatus,
    }),
    [state, transitionStatus],
  );

  const element = useRenderElement('div', componentProps, {
    state: panelState,
    ref: [forwardedRef, panelRef],
    props: [
      props,
      {
        style: {
          [CollapsiblePanelCssVars.collapsiblePanelHeight as string]:
            height === undefined ? 'auto' : `${height}px`,
          [CollapsiblePanelCssVars.collapsiblePanelWidth as string]:
            width === undefined ? 'auto' : `${width}px`,
        },
      },
      elementProps,
    ],
    customStyleHookMapping: collapsibleStyleHookMapping,
  });

  const shouldRender = keepMounted || hiddenUntilFound || (!keepMounted && mounted);

  if (!shouldRender) {
    return null;
  }

  return element;
});

export namespace CollapsiblePanel {
  export interface State extends CollapsibleRoot.State {
    transitionStatus: TransitionStatus;
  }

  export interface Props extends BaseUIComponentProps<'div', CollapsibleRoot.State> {
    /**
     * Allows the browser’s built-in page search to find and expand the panel contents.
     *
     * Overrides the `keepMounted` prop and uses `hidden="until-found"`
     * to hide the element without removing it from the DOM.
     *
     * @default false
     */
    hiddenUntilFound?: boolean;
    /**
     * Whether to keep the element in the DOM while the panel is hidden.
     * This prop is ignored when `hiddenUntilFound` is used.
     * @default false
     */
    keepMounted?: boolean;
  }
}

// packages/solid/src/collapsible/panel/CollapsiblePanel.tsx
'use client';
import { type Accessor, createEffect, onCleanup, Show, splitProps } from 'solid-js';
import { BaseUIComponentProps } from '../../utils/types';
import { useForkRefN } from '../../utils/useForkRef';
import { useOpenChangeComplete } from '../../utils/useOpenChangeComplete';
import { RenderElement } from '../../utils/useRenderElement';
import type { TransitionStatus } from '../../utils/useTransitionStatus';
import { warn } from '../../utils/warn';
import type { CollapsibleRoot } from '../root/CollapsibleRoot';
import { useCollapsibleRootContext } from '../root/CollapsibleRootContext';
import { collapsibleStyleHookMapping } from '../root/styleHooks';
import { CollapsiblePanelCssVars } from './CollapsiblePanelCssVars';
import { useCollapsiblePanel } from './useCollapsiblePanel';

/**
 * A panel with the collapsible contents.
 * Renders a `<div>` element.
 *
 * Documentation: [Base UI Collapsible](https://base-ui.com/react/components/collapsible)
 */
export function CollapsiblePanel(componentProps: CollapsiblePanel.Props) {
  const [local, elementProps] = splitProps(componentProps, [
    'class',
    'hiddenUntilFound',
    'keepMounted',
    'render',
    'id',
  ]);

  if (process.env.NODE_ENV !== 'production') {
    createEffect(() => {
      if (local.hiddenUntilFound && local.keepMounted === false) {
        warn(
          'The `keepMounted={false}` prop on a Collapsible will be ignored when using `hiddenUntilFound` since it requires the Panel to remain mounted even when closed.',
        );
      }
    });
  }

  const context = useCollapsibleRootContext();

  const hiddenUntilFound = () => local.hiddenUntilFound ?? false;
  const keepMounted = () => local.keepMounted ?? false;

  createEffect(() => {
    if (local.id) {
      context.setPanelIdState(local.id);

      onCleanup(() => {
        context.setPanelIdState(undefined);
      });
    }
  });

  createEffect(() => {
    context.setHiddenUntilFound(hiddenUntilFound());
  });

  createEffect(() => {
    context.setKeepMounted(keepMounted());
  });

  const panel = useCollapsiblePanel({
    abortControllerRef: context.abortControllerRef,
    animationTypeRef: context.animationTypeRef,
    // TODO: fix the type
    externalRef: elementProps.ref,
    height: context.height,
    hiddenUntilFound,
    id: context.panelId,
    keepMounted,
    mounted: context.mounted,
    onOpenChange: context.onOpenChange,
    open: context.open,
    panelRef: context.panelRef,
    runOnceAnimationsFinish: context.runOnceAnimationsFinish,
    setDimensions: context.setDimensions,
    setMounted: context.setMounted,
    setOpen: context.setOpen,
    setVisible: context.setVisible,
    transitionDimensionRef: context.transitionDimensionRef,
    visible: context.visible,
    width: context.width,
  });

  useOpenChangeComplete({
    open: context.open,
    ref: context.panelRef,
    onComplete() {
      if (!context.open()) {
        return;
      }

      context.setDimensions({ height: undefined, width: undefined });
    },
  });

  const panelState: CollapsiblePanel.State = {
    ...context.state,
    transitionStatus: context.transitionStatus,
  };

  const shouldRender = () =>
    keepMounted() || hiddenUntilFound() || (!keepMounted() && context.mounted());

  return (
    <Show when={shouldRender()} fallback={null}>
      <RenderElement
        element="div"
        componentProps={componentProps}
        params={{
          state: panelState,
          ref: useForkRefN(elementProps.ref, (el) => {
            panel.ref = el as HTMLDivElement;
          }),
          props: [
            panel.props(),
            {
              style: {
                [CollapsiblePanelCssVars.collapsiblePanelHeight as string]:
                  context.height() === undefined ? 'auto' : `${context.height()}px`,
                [CollapsiblePanelCssVars.collapsiblePanelWidth as string]:
                  context.width() === undefined ? 'auto' : `${context.width()}px`,
              },
            },
            elementProps as any,
          ],
          customStyleHookMapping: collapsibleStyleHookMapping,
        }}
      />
    </Show>
  );
}

export namespace CollapsiblePanel {
  export interface State extends CollapsibleRoot.State {
    transitionStatus: Accessor<TransitionStatus>;
  }

  export interface Props extends BaseUIComponentProps<'div', CollapsibleRoot.State> {
    /**
     * Allows the browser’s built-in page search to find and expand the panel contents.
     *
     * Overrides the `keepMounted` prop and uses `hidden="until-found"`
     * to hide the element without removing it from the DOM.
     *
     * @default false
     */
    hiddenUntilFound?: boolean;
    /**
     * Whether to keep the element in the DOM while the panel is hidden.
     * This prop is ignored when `hiddenUntilFound` is used.
     * @default false
     */
    keepMounted?: boolean;
  }
}
