// packages/solid/src/utils/useRenderElement.tsx
import { createMemo, Match, Show, Switch, type Accessor, type JSX, type Ref } from 'solid-js';
import { Dynamic } from 'solid-js/web';
import { mergeClasses, mergePropsN } from '../merge-props';
import { EMPTY_OBJECT } from './constants';
import { CustomStyleHookMapping, getStyleHookProps } from './getStyleHookProps';
import { mergeObjects } from './mergeObjects';
import { resolveClassName } from './resolveClassName';
import type { ComponentRenderFn, HTMLProps } from './types';
import { useForkRefN } from './useForkRef';

type IntrinsicTagName = keyof JSX.IntrinsicElements;

export function RenderElement<
  State extends Record<string, any>,
  RenderedElementType extends HTMLElement,
  TagName extends IntrinsicTagName | undefined,
  Enabled extends boolean | undefined = undefined,
>(props: {
  element: TagName;
  componentProps: RenderElement.ComponentProps<State>;
  params: RenderElement.Parameters<State, RenderedElementType, TagName, Enabled>;
}): JSX.Element {
  const state = () => props.params.state?.() ?? (EMPTY_OBJECT as State);
  const enabled = () => props.params.enabled?.() ?? true;
  const className = () =>
    enabled() ? resolveClassName(props.componentProps.class, state()) : undefined;

  const styleHooks = createMemo((): Record<string, string> | undefined => {
    if (props.params.disableStyleHooks !== true) {
      return enabled()
        ? getStyleHookProps(state(), props.params.customStyleHookMapping)
        : EMPTY_OBJECT;
    }
    return undefined;
  });

  const propsParams = createMemo(() =>
    Array.isArray(props.params.props?.())
      ? mergePropsN(props.params.props!() as any[])
      : props.params.props?.(),
  );

  const outProps = createMemo((): JSX.HTMLAttributes<any> => {
    if (enabled()) {
      const mergedProps: JSX.HTMLAttributes<any> =
        mergeObjects(styleHooks(), propsParams()) ?? EMPTY_OBJECT;

      if (className() !== undefined) {
        mergedProps.class = mergeClasses(mergedProps.class, className());
      }

      mergedProps.ref = useForkRefN([
        mergedProps.ref,
        ...(Array.isArray(props.params.ref) ? props.params.ref : [props.params.ref]),
      ]);

      return mergedProps;
    }

    return EMPTY_OBJECT;
  });

  return (
    <Switch fallback={null}>
      <Match when={enabled() === false}>{null}</Match>

      <Match when={props.componentProps.render}>
        <Show
          when={typeof props.componentProps.render === 'function' && props.componentProps.render}
          fallback={<Dynamic component={() => props.componentProps.render as JSX.Element} />}
        >
          {(renderer) => {
            const element = renderer()(outProps() as any, state());
            return element;
          }}
        </Show>
      </Match>

      <Match when={props.element && typeof props.element === 'string'}>
        <Dynamic
          component={props.element}
          {...(props.element === 'button' ? { type: 'button' } : {})}
          {...(props.element === 'img' ? { alt: '' } : {})}
          {...outProps()}
          ref={(el) => {
            outProps().ref = useForkRefN([
              outProps().ref,
              ...(Array.isArray(props.params.ref) ? props.params.ref : [props.params.ref]),
            ])(el);
          }}
        />
      </Match>
    </Switch>
  );
}

type RenderFunctionProps<TagName> = TagName extends keyof JSX.IntrinsicElements
  ? JSX.IntrinsicElements[TagName]
  : JSX.HTMLAttributes<any>;

export namespace RenderElement {
  export type Parameters<
    State,
    RenderedElementType extends HTMLElement,
    TagName,
    Enabled extends boolean | undefined,
  > = {
    /**
     * If `false`, the hook will skip most of its internal logic and return `null`.
     * This is useful for rendering a component conditionally.
     * @default true
     */
    enabled?: Accessor<Enabled>;
    /**
     * @deprecated
     */
    propGetter?: (externalProps: HTMLProps) => HTMLProps;
    /**
     * The ref to apply to the rendered element.
     */
    ref?:
      | Ref<RenderedElementType | null | undefined>
      | Ref<RenderedElementType | null | undefined>[];
    /**
     * The state of the component.
     */
    state?: Accessor<State>;

    /**
     * Intrinsic props to be spread on the rendered element.
     */
    props?: Accessor<
      | RenderFunctionProps<TagName>
      | Array<
          | RenderFunctionProps<TagName>
          | undefined
          | ((props: RenderFunctionProps<TagName>) => RenderFunctionProps<TagName>)
        >
    >;
    /**
     * A mapping of state to style hooks.
     */
    customStyleHookMapping?: CustomStyleHookMapping<State>;
  } /* This typing ensures `disableStyleHookMapping` is constantly defined or undefined */ & (
    | {
        /**
         * Disable style hook mapping.
         */
        disableStyleHooks: true;
      }
    | {
        /**
         * Disable style hook mapping.
         */
        disableStyleHooks?: false;
      }
  );

  export interface ComponentProps<State> {
    /**
     * The class name to apply to the rendered element.
     * Can be a string or a function that accepts the state and returns a string.
     */
    class?: string | ((state: State) => string);
    /**
     * The render prop or Solid element to override the default element.
     */
    render?: ComponentRenderFn<Record<string, unknown>, State> | JSX.Element;
  }
}

// packages/react/src/utils/useRenderElement.tsx
import * as React from 'react';
import { mergeClassNames, mergeProps, mergePropsN } from '../merge-props';
import { EMPTY_OBJECT } from './constants';
import { CustomStyleHookMapping, getStyleHookProps } from './getStyleHookProps';
import { mergeObjects } from './mergeObjects';
import { isReactVersionAtLeast } from './reactVersion';
import { resolveClassName } from './resolveClassName';
import type { BaseUIComponentProps, ComponentRenderFn, HTMLProps } from './types';
import { useForkRef, useForkRefN } from './useForkRef';

type IntrinsicTagName = keyof React.JSX.IntrinsicElements;

/**
 * Renders a Base UI element.
 *
 * @param element The default HTML element to render. Can be overridden by the `render` prop.
 * @param componentProps An object containing the `render` and `className` props to be used for element customization. Other props are ignored.
 * @param params Additional parameters for rendering the element.
 */
export function useRenderElement<
  State extends Record<string, any>,
  RenderedElementType extends Element,
  TagName extends IntrinsicTagName | undefined,
  Enabled extends boolean | undefined = undefined,
>(
  element: TagName,
  componentProps: useRenderElement.ComponentProps<State>,
  params: useRenderElement.Parameters<State, RenderedElementType, TagName, Enabled> = {},
): Enabled extends false ? null : React.ReactElement<Record<string, unknown>> {
  const renderProp = componentProps.render;
  const outProps = useRenderElementProps(componentProps, params);
  if (params.enabled === false) {
    return null as Enabled extends false ? null : React.ReactElement<Record<string, unknown>>;
  }

  const state = params.state ?? (EMPTY_OBJECT as State);
  return evaluateRenderProp(element, renderProp, outProps, state) as Enabled extends false
    ? null
    : React.ReactElement<Record<string, unknown>>;
}

/**
 * Computes render element final props.
 */
function useRenderElementProps<
  State extends Record<string, any>,
  RenderedElementType extends Element,
  TagName extends IntrinsicTagName | undefined,
  Enabled extends boolean | undefined,
>(
  componentProps: useRenderElement.ComponentProps<State>,
  params: useRenderElement.Parameters<State, RenderedElementType, TagName, Enabled> = {},
): React.HTMLAttributes<any> & React.RefAttributes<any> {
  const { className: classNameProp, render: renderProp } = componentProps;

  const {
    state = EMPTY_OBJECT as State,
    ref,
    props,
    disableStyleHooks,
    customStyleHookMapping,
    enabled = true,
  } = params;

  const className = enabled ? resolveClassName(classNameProp, state) : undefined;

  let styleHooks: Record<string, string> | undefined;
  if (disableStyleHooks !== true) {
    // SAFETY: We use typings to ensure `disableStyleHooks` is either always set or
    // always unset, so this `if` block is stable across renders.

    styleHooks = React.useMemo(
      () => (enabled ? getStyleHookProps(state, customStyleHookMapping) : EMPTY_OBJECT),
      [state, customStyleHookMapping, enabled],
    );
  }

  const outProps: React.HTMLAttributes<any> & React.RefAttributes<any> = enabled
    ? (mergeObjects(styleHooks, Array.isArray(props) ? mergePropsN(props) : props) ?? EMPTY_OBJECT)
    : EMPTY_OBJECT;

  // SAFETY: The `useForkRef` functions use a single hook to store the same value,
  // switching between them at runtime is safe. If this assertion fails, React will
  // throw at runtime anyway.
  // This also skips the `useForkRef` call on the server, which is fine because
  // refs are not used on the server side.

  if (typeof document !== 'undefined') {
    if (!enabled) {
      useForkRef(null, null);
    } else if (Array.isArray(ref)) {
      outProps.ref = useForkRefN([outProps.ref, getChildRef(renderProp), ...ref]);
    } else {
      outProps.ref = useForkRef(outProps.ref, getChildRef(renderProp), ref);
    }
  }

  if (!enabled) {
    return EMPTY_OBJECT;
  }

  if (className !== undefined) {
    outProps.className = mergeClassNames(outProps.className, className);
  }

  return outProps;
}

function evaluateRenderProp<T extends React.ElementType, S>(
  element: IntrinsicTagName | undefined,
  render: BaseUIComponentProps<T, S>['render'],
  props: React.HTMLAttributes<any> & React.RefAttributes<any>,
  state: S,
): React.ReactElement<Record<string, unknown>> {
  if (render) {
    if (typeof render === 'function') {
      return render(props, state);
    }
    const mergedProps = mergeProps(props, render.props);
    mergedProps.ref = props.ref;
    return React.cloneElement(render, mergedProps);
  }
  if (element) {
    if (typeof element === 'string') {
      return renderTag(element, props);
    }
  }
  // Unreachable, but the typings on `useRenderElement` need to be reworked
  // to annotate it correctly.
  throw new Error('Base UI: Render element or function are not defined.');
}

function renderTag(Tag: string, props: Record<string, any>) {
  if (Tag === 'button') {
    return <button type="button" {...props} />;
  }
  if (Tag === 'img') {
    return <img alt="" {...props} />;
  }
  return React.createElement(Tag, props);
}

function getChildRef<ElementType extends React.ElementType, State>(
  render: BaseUIComponentProps<ElementType, State>['render'],
): React.RefCallback<any> | null {
  if (render && typeof render !== 'function') {
    return isReactVersionAtLeast(19) ? render.props.ref : render.ref;
  }
  return null;
}

type RenderFunctionProps<TagName> = TagName extends keyof React.JSX.IntrinsicElements
  ? React.JSX.IntrinsicElements[TagName]
  : React.HTMLAttributes<any>;

export namespace useRenderElement {
  export type Parameters<
    State,
    RenderedElementType extends Element,
    TagName,
    Enabled extends boolean | undefined,
  > = {
    /**
     * If `false`, the hook will skip most of its internal logic and return `null`.
     * This is useful for rendering a component conditionally.
     * @default true
     */
    enabled?: Enabled;
    /**
     * @deprecated
     */
    propGetter?: (externalProps: HTMLProps) => HTMLProps;
    /**
     * The ref to apply to the rendered element.
     */
    ref?: React.Ref<RenderedElementType> | (React.Ref<RenderedElementType> | undefined)[];
    /**
     * The state of the component.
     */
    state?: State;
    /**
     * Intrinsic props to be spread on the rendered element.
     */
    props?:
      | RenderFunctionProps<TagName>
      | Array<
          | RenderFunctionProps<TagName>
          | undefined
          | ((props: RenderFunctionProps<TagName>) => RenderFunctionProps<TagName>)
        >;
    /**
     * A mapping of state to style hooks.
     */
    customStyleHookMapping?: CustomStyleHookMapping<State>;
  } /* This typing ensures `disableStyleHookMapping` is constantly defined or undefined */ & (
    | {
        /**
         * Disable style hook mapping.
         */
        disableStyleHooks: true;
      }
    | {
        /**
         * Disable style hook mapping.
         */
        disableStyleHooks?: false;
      }
  );

  export interface ComponentProps<State> {
    /**
     * The class name to apply to the rendered element.
     * Can be a string or a function that accepts the state and returns a string.
     */
    className?: string | ((state: State) => string);
    /**
     * The render prop or React element to override the default element.
     */
    render?:
      | undefined
      | ComponentRenderFn<React.HTMLAttributes<any>, State>
      | React.ReactElement<Record<string, unknown>>;
  }
}
