// packages/react/src/form/Form.tsx
'use client';
import * as React from 'react';
import type { BaseUIComponentProps } from '../utils/types';
import { useEventCallback } from '../utils/useEventCallback';
import { useRenderElement } from '../utils/useRenderElement';
import { FormContext } from './FormContext';

const EMPTY = {};

/**
 * A native form element with consolidated error handling.
 * Renders a `<form>` element.
 *
 * Documentation: [Base UI Form](https://base-ui.com/react/components/form)
 */
export const Form = React.forwardRef(function Form(
  componentProps: Form.Props,
  forwardedRef: React.ForwardedRef<HTMLFormElement>,
) {
  const {
    render,
    className,
    errors,
    onClearErrors: onClearErrorsProp,
    onSubmit: onSubmitProp,
    ...elementProps
  } = componentProps;

  const formRef = React.useRef<FormContext['formRef']['current']>({
    fields: new Map(),
  });
  const submittedRef = React.useRef(false);

  const onSubmit = useEventCallback(onSubmitProp);
  const onClearErrors = useEventCallback(onClearErrorsProp);

  const focusControl = useEventCallback((control: HTMLElement) => {
    control.focus();
    if (control.tagName === 'INPUT') {
      (control as HTMLInputElement).select();
    }
  });

  React.useEffect(() => {
    if (!submittedRef.current) {
      return;
    }

    submittedRef.current = false;

    const invalidFields = Array.from(formRef.current.fields.values()).filter((field) => {
      return field.validityData.state.valid === false;
    });

    if (invalidFields.length) {
      focusControl(invalidFields[0].controlRef.current);
    }
  }, [errors, focusControl]);

  const element = useRenderElement('form', componentProps, {
    state: EMPTY,
    ref: forwardedRef,
    props: [
      {
        noValidate: true,
        onSubmit(event) {
          let values = Array.from(formRef.current.fields.values());

          // Async validation isn't supported to stop the submit event.
          values.forEach((field) => {
            field.validate();
          });

          values = Array.from(formRef.current.fields.values());

          const invalidFields = values.filter((field) => !field.validityData.state.valid);

          if (invalidFields.length) {
            event.preventDefault();
            focusControl(invalidFields[0].controlRef.current);
          } else {
            submittedRef.current = true;
            onSubmit(event as any);
          }
        },
      },
      elementProps,
    ],
  });

  const clearErrors = useEventCallback((name: string | undefined) => {
    if (name && errors && EMPTY.hasOwnProperty.call(errors, name)) {
      const nextErrors = { ...errors };
      delete nextErrors[name];
      onClearErrors(nextErrors);
    }
  });

  const contextValue: FormContext = React.useMemo(
    () => ({
      formRef,
      errors: errors ?? {},
      clearErrors,
    }),
    [formRef, errors, clearErrors],
  );

  return <FormContext.Provider value={contextValue}>{element}</FormContext.Provider>;
});

export namespace Form {
  export interface Props extends BaseUIComponentProps<'form', State> {
    /**
     * An object where the keys correspond to the `name` attribute of the form fields,
     * and the values correspond to the error(s) related to that field.
     */
    errors?: FormContext['errors'];
    /**
     * Event handler called when the `errors` object is cleared.
     */
    onClearErrors?: (errors: FormContext['errors']) => void;
  }
  export interface State {}
}

// packages/solid/src/form/Form.tsx
'use client';
import { createEffect, createMemo, on } from 'solid-js';
import { createStore } from 'solid-js/store';
import { access, callEventHandler, splitComponentProps } from '../solid-helpers';
import type { BaseUIComponentProps } from '../utils/types';
import { useRenderElement } from '../utils/useRenderElement';
import { FormContext } from './FormContext';

const EMPTY = {};

/**
 * A native form element with consolidated error handling.
 * Renders a `<form>` element.
 *
 * Documentation: [Base UI Form](https://base-ui.com/react/components/form)
 */
export function Form(componentProps: Form.Props) {
  const [, local, elementProps] = splitComponentProps(componentProps, [
    'errors',
    'onClearErrors',
    'onSubmit',
  ]);
  const [formRef, setFormRef] = createStore<FormContext['formRef']>({ fields: {} });
  let submitted = false;

  const focusControl = (control: HTMLElement) => {
    control.focus();
    if (control.tagName === 'INPUT') {
      (control as HTMLInputElement).select();
    }
  };

  const invalidFields = createMemo(() =>
    Object.values(formRef.fields).filter((field) => field.validityData.state.valid === false),
  );

  createEffect(
    on(invalidFields, () => {
      if (!submitted) {
        return;
      }

      submitted = false;

      if (invalidFields().length) {
        const controlRef = access(invalidFields()[0].controlRef);
        focusControl(controlRef);
      }
    }),
  );

  const clearErrors = (name: string | undefined) => {
    const err = local.errors;
    if (name && err && EMPTY.hasOwnProperty.call(err, name)) {
      const nextErrors = { ...err };
      delete nextErrors[name];
      local.onClearErrors?.(nextErrors);
    }
  };

  const contextValue: FormContext = {
    formRef,
    setFormRef,
    errors: () => local.errors ?? {},
    clearErrors,
  };

  const element = useRenderElement('form', componentProps, {
    state: EMPTY,
    props: [
      {
        noValidate: true,
        onSubmit(event) {
          // Async validation isn't supported to stop the submit event.
          Object.values(formRef.fields).forEach((field) => field.validate());

          if (invalidFields().length) {
            event.preventDefault();
            const controlRef = access(invalidFields()[0].controlRef);
            focusControl(controlRef);
          } else {
            submitted = true;
            callEventHandler(local.onSubmit, event);
          }
        },
      },
      elementProps,
    ],
  });

  return <FormContext.Provider value={contextValue}>{element()}</FormContext.Provider>;
}

export namespace Form {
  export interface Props extends BaseUIComponentProps<'form', State> {
    /**
     * An object where the keys correspond to the `name` attribute of the form fields,
     * and the values correspond to the error(s) related to that field.
     */
    errors?: ReturnType<FormContext['errors']>;
    /**
     * Event handler called when the `errors` object is cleared.
     */
    onClearErrors?: (errors: ReturnType<FormContext['errors']>) => void;
  }
  export interface State {}
}
