// packages/react/src/utils/useOpenChangeComplete.tsx
'use client';
import * as React from 'react';
import { useAnimationsFinished } from './useAnimationsFinished';
import { useEventCallback } from './useEventCallback';
import { useLatestRef } from './useLatestRef';

/**
 * Calls the provided function when the CSS open/close animation or transition completes.
 */
export function useOpenChangeComplete(parameters: useOpenChangeComplete.Parameters) {
  const { enabled = true, open, ref, onComplete: onCompleteParam } = parameters;

  const openRef = useLatestRef(open);
  const onComplete = useEventCallback(onCompleteParam);
  const runOnceAnimationsFinish = useAnimationsFinished(ref, open);

  React.useEffect(() => {
    if (!enabled) {
      return;
    }

    runOnceAnimationsFinish(() => {
      console.log('useOpenChangeComplete', { open, openRef: openRef.current });
      if (open === openRef.current) {
        onComplete();
      }
    });
  }, [enabled, open, onComplete, runOnceAnimationsFinish, openRef]);
}

export namespace useOpenChangeComplete {
  export interface Parameters {
    /**
     * Whether the hook is enabled.
     * @default true
     */
    enabled?: boolean;
    /**
     * Whether the element is open.
     */
    open?: boolean;
    /**
     * Ref to the element being closed.
     */
    ref: React.RefObject<HTMLElement | null>;
    /**
     * Function to call when the animation completes (or there is no animation).
     */
    onComplete: () => void;
  }
}

// packages/solid/src/utils/useOpenChangeComplete.tsx
'use client';

import { Accessor, createEffect } from 'solid-js';
import { useAnimationsFinished } from './useAnimationsFinished';

/**
 * Calls the provided function when the CSS open/close animation or transition completes.
 */
export function useOpenChangeComplete<T extends HTMLElement>(
  parameters: useOpenChangeComplete.Parameters<T>,
) {
  const enabled = () => parameters.enabled ?? true;
  let openRef = parameters.open?.();
  const runOnceAnimationsFinish = useAnimationsFinished(parameters.ref, parameters.open);

  createEffect(() => {
    if (!enabled()) {
      return;
    }

    runOnceAnimationsFinish(() => {
      if (parameters.open?.() === openRef) {
        parameters.onComplete();
      }
    });
  });
}

export namespace useOpenChangeComplete {
  export interface Parameters<T extends HTMLElement> {
    /**
     * Whether the hook is enabled.
     * @default true
     */
    enabled?: boolean;
    /**
     * Whether the element is open.
     */
    open?: Accessor<boolean | undefined>;
    /**
     * Ref to the element being closed.
     */
    ref: T | null | undefined;
    /**
     * Function to call when the animation completes (or there is no animation).
     */
    onComplete: () => void;
  }
}
