// packages/solid/src/dialog/portal/DialogPortalContext.ts
import { createContext, useContext, type Accessor } from 'solid-js';

export const DialogPortalContext = createContext<Accessor<boolean | undefined>>(() => undefined);

export function useDialogPortalContext() {
  const value = useContext(DialogPortalContext);
  if (value === undefined) {
    throw new Error('Base UI: <Dialog.Portal> is missing.');
  }
  return value;
}

// packages/react/src/dialog/portal/DialogPortalContext.ts
import * as React from 'react';

export const DialogPortalContext = React.createContext<boolean | undefined>(undefined);

export function useDialogPortalContext() {
  const value = React.useContext(DialogPortalContext);
  if (value === undefined) {
    throw new Error('Base UI: <Dialog.Portal> is missing.');
  }

  return value;
}
