// packages/solid/src/field/useField.ts
import { createEffect, onCleanup } from 'solid-js';
import { useFormContext } from '../form/FormContext';
import { type MaybeAccessor, access } from '../solid-helpers';
import { useFieldRootContext } from './root/FieldRootContext';
import { getCombinedFieldValidityData } from './utils/getCombinedFieldValidityData';

export function useField(params: useField.Parameters) {
  const { formRef, setFormRef } = useFormContext();
  const { invalid, refs, validityData, setValidityData } = useFieldRootContext();
  const enabled = () => access(params.enabled) ?? true;
  const value = () => access(params.value);
  const id = () => access(params.id);
  const name = () => access(params.name);
  const controlRef = () => access(params.controlRef);

  createEffect(() => {
    if (!enabled()) {
      return;
    }

    let initialValue = value();
    if (initialValue === undefined) {
      initialValue = params.getValue?.();
    }

    if (validityData.initialValue === null && initialValue !== validityData.initialValue) {
      setValidityData((prev) => ({ ...prev, initialValue }));
    }
  });

  createEffect(() => {
    if (!enabled()) {
      return;
    }

    const idValue = id();
    if (idValue) {
      console.log('setting field', idValue, validityData);

      formRef.fields.set(idValue, {
        controlRef: controlRef(),
        validityData: getCombinedFieldValidityData(validityData, invalid()),
        validate() {
          let nextValue = value();
          if (nextValue === undefined) {
            nextValue = params.getValue?.();
          }

          refs.markedDirtyRef = true;
          // Synchronously update the validity state so the submit event can be prevented.
          params.commitValidation(nextValue);
        },
        getValueRef: params.getValue,
        name: name(),
      });
    }
  });

  createEffect(() => {
    const fields = formRef.fields;
    const idValue = id();
    onCleanup(() => {
      if (idValue) {
        fields.delete(idValue);
      }
    });
  });
}

export namespace useField {
  export interface Parameters {
    enabled?: MaybeAccessor<boolean | undefined>;
    value: MaybeAccessor<unknown>;
    getValue?: (() => unknown) | undefined;
    id: MaybeAccessor<string | undefined>;
    name?: MaybeAccessor<string | undefined>;
    commitValidation: (value: unknown) => void;
    /**
     * A ref to a focusable element that receives focus when the field fails
     * validation during form submission.
     */
    controlRef: MaybeAccessor<any>;
  }
}

// packages/react/src/field/useField.ts
import * as ReactDOM from 'react-dom';
import { useFormContext } from '../form/FormContext';
import { useLatestRef } from '../utils/useLatestRef';
import { useModernLayoutEffect } from '../utils/useModernLayoutEffect';
import { useFieldRootContext } from './root/FieldRootContext';
import { getCombinedFieldValidityData } from './utils/getCombinedFieldValidityData';

export function useField(params: useField.Parameters) {
  const { formRef } = useFormContext();
  const { invalid, markedDirtyRef, validityData, setValidityData } = useFieldRootContext();
  const { enabled = true, value, id, name, controlRef, commitValidation } = params;

  const getValueRef = useLatestRef(params.getValue);

  useModernLayoutEffect(() => {
    if (!enabled) {
      return;
    }

    let initialValue = value;
    if (initialValue === undefined) {
      initialValue = getValueRef.current?.();
    }

    if (validityData.initialValue === null && initialValue !== validityData.initialValue) {
      setValidityData((prev) => ({ ...prev, initialValue }));
    }
  }, [enabled, setValidityData, value, validityData.initialValue, getValueRef]);

  useModernLayoutEffect(() => {
    if (!enabled) {
      return;
    }

    if (id) {
      console.log('setting field', id, {
        invalid,
        old: validityData,
        new: getCombinedFieldValidityData(validityData, invalid),
      });
      formRef.current.fields.set(id, {
        controlRef,
        validityData: getCombinedFieldValidityData(validityData, invalid),
        validate() {
          let nextValue = value;
          if (nextValue === undefined) {
            nextValue = getValueRef.current?.();
          }

          markedDirtyRef.current = true;

          // Synchronously update the validity state so the submit event can be prevented.
          console.log('FLUSHING SYNC', nextValue);
          ReactDOM.flushSync(
            () => (console.log('FLUSHED SYNC', nextValue), commitValidation(nextValue)),
          );
        },
        getValueRef,
        name,
      });
    }
  }, [
    commitValidation,
    controlRef,
    enabled,
    formRef,
    getValueRef,
    id,
    invalid,
    markedDirtyRef,
    name,
    validityData,
    value,
  ]);

  useModernLayoutEffect(() => {
    const fields = formRef.current.fields;
    return () => {
      if (id) {
        fields.delete(id);
      }
    };
  }, [formRef, id]);
}

export namespace useField {
  export interface Parameters {
    enabled?: boolean;
    value: unknown;
    getValue?: (() => unknown) | undefined;
    id: string | undefined;
    name?: string | undefined;
    commitValidation: (value: unknown) => void;
    /**
     * A ref to a focusable element that receives focus when the field fails
     * validation during form submission.
     */
    controlRef: React.RefObject<any>;
  }
}
