// packages/solid/src/collapsible/root/useCollapsibleRoot.ts
'use client';
import { createEffect, createSignal, on, type Accessor, type JSX, type Setter } from 'solid-js';
import { useAnimationsFinished } from '../../utils/useAnimationsFinished';
import { useBaseUiId } from '../../utils/useBaseUiId';
import { useControlled } from '../../utils/useControlled';
import { TransitionStatus, useTransitionStatus } from '../../utils/useTransitionStatus';

export type AnimationType = 'css-transition' | 'css-animation' | 'none' | null;

export interface Dimensions {
  height: number | undefined;
  width: number | undefined;
}

export function useCollapsibleRoot(
  parameters: useCollapsibleRoot.Parameters,
): useCollapsibleRoot.ReturnValue {
  const isControlled = () => parameters.open?.() !== undefined;

  const [open, setOpen] = useControlled({
    controlled: () => parameters.open?.(),
    default: () => parameters.defaultOpen?.(),
    name: 'Collapsible',
    state: 'open',
  });

  const [state, setState] = useTransitionStatus(open, true, true);
  const [visible, setVisible] = createSignal(open());
  const [dimensions, setDimensions] = createSignal<Dimensions>({
    height: undefined,
    width: undefined,
  });

  const defaultPanelId = useBaseUiId();
  const [panelIdState, setPanelIdState] = createSignal<string | undefined>();
  const panelId = () => panelIdState() ?? defaultPanelId();

  const [hiddenUntilFound, setHiddenUntilFound] = createSignal(false);
  const [keepMounted, setKeepMounted] = createSignal(false);

  let abortControllerRef = null as AbortController | null;
  const animationTypeRef: AnimationType = null;
  const transitionDimensionRef: 'width' | 'height' | null = null;

  let panelRef = null as HTMLElement | null;

  const runOnceAnimationsFinish = useAnimationsFinished(panelRef, () => false);

  function handleTrigger() {
    const nextOpen = !open();

    if (animationTypeRef === 'css-animation' && panelRef != null) {
      panelRef.style.removeProperty('animation-name');
    }

    if (!hiddenUntilFound() && !keepMounted()) {
      if (animationTypeRef != null && animationTypeRef !== 'css-animation') {
        if (!state.mounted && nextOpen) {
          setState('mounted', true);
        }
      }

      if (animationTypeRef === 'css-animation') {
        if (!visible() && nextOpen) {
          setVisible(true);
        }
        if (!state.mounted && nextOpen) {
          setState('mounted', true);
        }
      }
    }

    setOpen(nextOpen);
    parameters.onOpenChange(nextOpen);

    if (animationTypeRef === 'none') {
      if (state.mounted && !nextOpen) {
        setState('mounted', false);
      }
    }
  }

  createEffect(
    on([open, keepMounted, () => parameters.open?.(), isControlled], () => {
      /**
       * Unmount immediately when closing in controlled mode and keepMounted={false}
       * and no CSS animations or transitions are applied
       */
      if (isControlled() && animationTypeRef === 'none' && !keepMounted() && !open()) {
        setState('mounted', false);
      }
    }),
  );

  return {
    abortControllerRef,
    animationTypeRef,
    disabled: parameters.disabled,
    handleTrigger,
    height: () => dimensions().height,
    mounted: () => state.mounted,
    open,
    panelId,
    panelRef,
    runOnceAnimationsFinish,
    setDimensions,
    setHiddenUntilFound,
    setKeepMounted,
    setMounted: (mounted) => setState('mounted', mounted),
    setOpen,
    setPanelIdState,
    setVisible,
    transitionDimensionRef,
    transitionStatus: () => state.transitionStatus,
    visible,
    width: () => dimensions().width,
  };
}

export namespace useCollapsibleRoot {
  export interface Parameters {
    /**
     * Whether the collapsible panel is currently open.
     *
     * To render an uncontrolled collapsible, use the `defaultOpen` prop instead.
     */
    open?: Accessor<boolean | undefined>;
    /**
     * Whether the collapsible panel is initially open.
     *
     * To render a controlled collapsible, use the `open` prop instead.
     * @default false
     */
    defaultOpen?: Accessor<boolean | undefined>;
    /**
     * Event handler called when the panel is opened or closed.
     */
    onOpenChange: (open: boolean) => void;
    /**
     * Whether the component should ignore user interaction.
     * @default false
     */
    disabled: Accessor<boolean>;
  }

  export interface ReturnValue {
    abortControllerRef: AbortController | null;
    animationTypeRef: AnimationType;
    /**
     * Whether the component should ignore user interaction.
     */
    disabled: Accessor<boolean>;
    handleTrigger: () => void;
    /**
     * The height of the panel.
     */
    height: Accessor<number | undefined>;
    /**
     * Whether the collapsible panel is currently mounted.
     */
    mounted: Accessor<boolean>;
    /**
     * Whether the collapsible panel is currently open.
     */
    open: Accessor<boolean>;
    panelId: Accessor<JSX.HTMLAttributes<Element>['id']>;
    panelRef: HTMLElement | null;
    runOnceAnimationsFinish: (fnToExecute: () => void, signal?: AbortSignal | null) => void;
    setDimensions: Setter<Dimensions>;
    setHiddenUntilFound: Setter<boolean>;
    setKeepMounted: Setter<boolean>;
    setMounted: (open: boolean) => void;
    setOpen: (open: boolean) => void;
    setPanelIdState: (id: string | undefined) => void;
    setVisible: Setter<boolean>;
    transitionDimensionRef: 'height' | 'width' | null;
    transitionStatus: Accessor<TransitionStatus>;
    /**
     * The visible state of the panel used to determine the `[hidden]` attribute
     * only when CSS keyframe animations are used.
     */
    visible: Accessor<boolean>;
    /**
     * The width of the panel.
     */
    width: Accessor<number | undefined>;
  }
}

// packages/react/src/collapsible/root/useCollapsibleRoot.ts
'use client';
import * as React from 'react';
import { useAnimationsFinished } from '../../utils/useAnimationsFinished';
import { useBaseUiId } from '../../utils/useBaseUiId';
import { useControlled } from '../../utils/useControlled';
import { useEventCallback } from '../../utils/useEventCallback';
import { useModernLayoutEffect } from '../../utils/useModernLayoutEffect';
import { TransitionStatus, useTransitionStatus } from '../../utils/useTransitionStatus';

export type AnimationType = 'css-transition' | 'css-animation' | 'none' | null;

export interface Dimensions {
  height: number | undefined;
  width: number | undefined;
}

export function useCollapsibleRoot(
  parameters: useCollapsibleRoot.Parameters,
): useCollapsibleRoot.ReturnValue {
  const { open: openParam, defaultOpen, onOpenChange, disabled } = parameters;

  const isControlled = openParam !== undefined;

  const [open, setOpen] = useControlled({
    controlled: openParam,
    default: defaultOpen,
    name: 'Collapsible',
    state: 'open',
  });

  const { mounted, setMounted, transitionStatus } = useTransitionStatus(open, true, true);
  const [visible, setVisible] = React.useState(open);
  const [{ height, width }, setDimensions] = React.useState<Dimensions>({
    height: undefined,
    width: undefined,
  });

  const defaultPanelId = useBaseUiId();
  const [panelIdState, setPanelIdState] = React.useState<string | undefined>();
  const panelId = panelIdState ?? defaultPanelId;

  const [hiddenUntilFound, setHiddenUntilFound] = React.useState(false);
  const [keepMounted, setKeepMounted] = React.useState(false);

  const abortControllerRef = React.useRef<AbortController | null>(null);
  const animationTypeRef = React.useRef<AnimationType>(null);
  const transitionDimensionRef = React.useRef<'width' | 'height' | null>(null);
  const panelRef: React.RefObject<HTMLElement | null> = React.useRef(null);

  const runOnceAnimationsFinish = useAnimationsFinished(panelRef, false);

  const handleTrigger = useEventCallback(() => {
    const nextOpen = !open;

    const panel = panelRef.current;

    if (animationTypeRef.current === 'css-animation' && panel != null) {
      panel.style.removeProperty('animation-name');
    }

    if (!hiddenUntilFound && !keepMounted) {
      if (animationTypeRef.current != null && animationTypeRef.current !== 'css-animation') {
        if (!mounted && nextOpen) {
          setMounted(true);
        }
      }

      if (animationTypeRef.current === 'css-animation') {
        if (!visible && nextOpen) {
          setVisible(true);
        }
        if (!mounted && nextOpen) {
          setMounted(true);
        }
      }
    }

    setOpen(nextOpen);
    onOpenChange(nextOpen);

    if (animationTypeRef.current === 'none') {
      if (mounted && !nextOpen) {
        setMounted(false);
      }
    }
  });

  useModernLayoutEffect(() => {
    /**
     * Unmount immediately when closing in controlled mode and keepMounted={false}
     * and no CSS animations or transitions are applied
     */
    if (isControlled && animationTypeRef.current === 'none' && !keepMounted && !open) {
      setMounted(false);
    }
  }, [isControlled, keepMounted, open, openParam, setMounted]);

  return React.useMemo(
    () => ({
      abortControllerRef,
      animationTypeRef,
      disabled,
      handleTrigger,
      height,
      mounted,
      open,
      panelId,
      panelRef,
      runOnceAnimationsFinish,
      setDimensions,
      setHiddenUntilFound,
      setKeepMounted,
      setMounted,
      setOpen,
      setPanelIdState,
      setVisible,
      transitionDimensionRef,
      transitionStatus,
      visible,
      width,
    }),
    [
      abortControllerRef,
      animationTypeRef,
      disabled,
      handleTrigger,
      height,
      mounted,
      open,
      panelId,
      panelRef,
      runOnceAnimationsFinish,
      setDimensions,
      setHiddenUntilFound,
      setKeepMounted,
      setMounted,
      setOpen,
      setVisible,
      transitionDimensionRef,
      transitionStatus,
      visible,
      width,
    ],
  );
}

export namespace useCollapsibleRoot {
  export interface Parameters {
    /**
     * Whether the collapsible panel is currently open.
     *
     * To render an uncontrolled collapsible, use the `defaultOpen` prop instead.
     */
    open?: boolean;
    /**
     * Whether the collapsible panel is initially open.
     *
     * To render a controlled collapsible, use the `open` prop instead.
     * @default false
     */
    defaultOpen?: boolean;
    /**
     * Event handler called when the panel is opened or closed.
     */
    onOpenChange: (open: boolean) => void;
    /**
     * Whether the component should ignore user interaction.
     * @default false
     */
    disabled: boolean;
  }

  export interface ReturnValue {
    abortControllerRef: React.RefObject<AbortController | null>;
    animationTypeRef: React.RefObject<AnimationType>;
    /**
     * Whether the component should ignore user interaction.
     */
    disabled: boolean;
    handleTrigger: () => void;
    /**
     * The height of the panel.
     */
    height: number | undefined;
    /**
     * Whether the collapsible panel is currently mounted.
     */
    mounted: boolean;
    /**
     * Whether the collapsible panel is currently open.
     */
    open: boolean;
    panelId: React.HTMLAttributes<Element>['id'];
    panelRef: React.RefObject<HTMLElement | null>;
    runOnceAnimationsFinish: (fnToExecute: () => void, signal?: AbortSignal | null) => void;
    setDimensions: React.Dispatch<React.SetStateAction<Dimensions>>;
    setHiddenUntilFound: React.Dispatch<React.SetStateAction<boolean>>;
    setKeepMounted: React.Dispatch<React.SetStateAction<boolean>>;
    setMounted: (open: boolean) => void;
    setOpen: (open: boolean) => void;
    setPanelIdState: (id: string | undefined) => void;
    setVisible: React.Dispatch<React.SetStateAction<boolean>>;
    transitionDimensionRef: React.RefObject<'height' | 'width' | null>;
    transitionStatus: TransitionStatus;
    /**
     * The visible state of the panel used to determine the `[hidden]` attribute
     * only when CSS keyframe animations are used.
     */
    visible: boolean;
    /**
     * The width of the panel.
     */
    width: number | undefined;
  }
}
