// packages/react/src/dialog/popup/DialogPopup.tsx
'use client';
import * as React from 'react';
import { FloatingFocusManager } from '../../floating-ui-react';
import { type CustomStyleHookMapping } from '../../utils/getStyleHookProps';
import { inertValue } from '../../utils/inertValue';
import { InternalBackdrop } from '../../utils/InternalBackdrop';
import { popupStateMapping as baseMapping } from '../../utils/popupStateMapping';
import { transitionStatusMapping } from '../../utils/styleHookMapping';
import { type BaseUIComponentProps } from '../../utils/types';
import { InteractionType } from '../../utils/useEnhancedClickHandler';
import { useForkRef } from '../../utils/useForkRef';
import { useOpenChangeComplete } from '../../utils/useOpenChangeComplete';
import { useRenderElement } from '../../utils/useRenderElement';
import { type TransitionStatus } from '../../utils/useTransitionStatus';
import { useDialogPortalContext } from '../portal/DialogPortalContext';
import { useDialogRootContext } from '../root/DialogRootContext';
import { DialogPopupCssVars } from './DialogPopupCssVars';
import { DialogPopupDataAttributes } from './DialogPopupDataAttributes';
import { useDialogPopup } from './useDialogPopup';

const customStyleHookMapping: CustomStyleHookMapping<DialogPopup.State> = {
  ...baseMapping,
  ...transitionStatusMapping,
  nestedDialogOpen(value) {
    return value ? { [DialogPopupDataAttributes.nestedDialogOpen]: '' } : null;
  },
};

/**
 * A container for the dialog contents.
 * Renders a `<div>` element.
 *
 * Documentation: [Base UI Dialog](https://base-ui.com/react/components/dialog)
 */
export const DialogPopup = React.forwardRef(function DialogPopup(
  componentProps: DialogPopup.Props,
  forwardedRef: React.ForwardedRef<HTMLDivElement>,
) {
  const { className, finalFocus, initialFocus, render, ...elementProps } = componentProps;

  const {
    descriptionElementId,
    dismissible,
    floatingRootContext,
    getPopupProps,
    modal,
    mounted,
    nested,
    nestedOpenDialogCount,
    setOpen,
    open,
    openMethod,
    popupRef,
    setPopupElement,
    titleElementId,
    transitionStatus,
    onOpenChangeComplete,
    internalBackdropRef,
  } = useDialogRootContext();

  useDialogPortalContext();

  useOpenChangeComplete({
    open,
    ref: popupRef,
    onComplete() {
      if (open) {
        onOpenChangeComplete?.(true);
      }
    },
  });

  const mergedRef = useForkRef(forwardedRef, popupRef);

  const { popupProps, resolvedInitialFocus } = useDialogPopup({
    descriptionElementId,
    initialFocus,
    modal,
    mounted,
    setOpen,
    openMethod,
    ref: mergedRef,
    setPopupElement,
    titleElementId,
  });

  const nestedDialogOpen = nestedOpenDialogCount > 0;

  const state: DialogPopup.State = React.useMemo(
    () => ({
      open,
      nested,
      transitionStatus,
      nestedDialogOpen,
    }),
    [open, nested, transitionStatus, nestedDialogOpen],
  );

  const element = useRenderElement('div', componentProps, {
    state,
    props: [
      getPopupProps(),
      popupProps,
      {
        style: {
          [DialogPopupCssVars.nestedDialogs]: nestedOpenDialogCount,
        } as React.CSSProperties,
      },
      elementProps,
    ],
    customStyleHookMapping,
  });

  return (
    <React.Fragment>
      {mounted && modal === true && (
        <InternalBackdrop ref={internalBackdropRef} inert={inertValue(!open)} />
      )}
      <FloatingFocusManager
        context={floatingRootContext}
        disabled={!mounted}
        closeOnFocusOut={dismissible}
        initialFocus={resolvedInitialFocus}
        returnFocus={finalFocus}
        modal={modal !== false}
      >
        {element}
      </FloatingFocusManager>
    </React.Fragment>
  );
});

export namespace DialogPopup {
  export interface Props extends BaseUIComponentProps<'div', State> {
    /**
     * Determines the element to focus when the dialog is opened.
     * By default, the first focusable element is focused.
     */
    initialFocus?:
      | React.RefObject<HTMLElement | null>
      | ((interactionType: InteractionType) => React.RefObject<HTMLElement | null>);
    /**
     * Determines the element to focus when the dialog is closed.
     * By default, focus returns to the trigger.
     */
    finalFocus?: React.RefObject<HTMLElement | null>;
  }

  export interface State {
    /**
     * Whether the dialog is currently open.
     */
    open: boolean;
    transitionStatus: TransitionStatus;
    /**
     * Whether the dialog is nested within a parent dialog.
     */
    nested: boolean;
    /**
     * Whether the dialog has nested dialogs open.
     */
    nestedDialogOpen: boolean;
  }
}

// packages/solid/src/dialog/popup/DialogPopup.tsx
'use client';
import type { JSX } from 'solid-js';
import { splitProps } from 'solid-js';
import { FloatingFocusManager } from '../../floating-ui-solid';
import { access, type MaybeAccessor } from '../../solid-helpers';
import { type CustomStyleHookMapping } from '../../utils/getStyleHookProps';
import { inertValue } from '../../utils/inertValue';
import { InternalBackdrop } from '../../utils/InternalBackdrop';
import { popupStateMapping as baseMapping } from '../../utils/popupStateMapping';
import { transitionStatusMapping } from '../../utils/styleHookMapping';
import { type BaseUIComponentProps } from '../../utils/types';
import { InteractionType } from '../../utils/useEnhancedClickHandler';
import { useForkRef } from '../../utils/useForkRef';
import { useOpenChangeComplete } from '../../utils/useOpenChangeComplete';
import { RenderElement } from '../../utils/useRenderElement';
import { type TransitionStatus } from '../../utils/useTransitionStatus';
import { useDialogPortalContext } from '../portal/DialogPortalContext';
import { useDialogRootContext } from '../root/DialogRootContext';
import { DialogPopupCssVars } from './DialogPopupCssVars';
import { DialogPopupDataAttributes } from './DialogPopupDataAttributes';
import { useDialogPopup } from './useDialogPopup';

const customStyleHookMapping: CustomStyleHookMapping<DialogPopup.State> = {
  ...baseMapping,
  ...transitionStatusMapping,
  nestedDialogOpen(value) {
    return access(value) ? { [DialogPopupDataAttributes.nestedDialogOpen]: '' } : null;
  },
};

/**
 * A container for the dialog contents.
 * Renders a `<div>` element.
 *
 * Documentation: [Base UI Dialog](https://base-ui.com/react/components/dialog)
 */
export function DialogPopup(componentProps: DialogPopup.Props) {
  const [local, elementProps] = splitProps(componentProps, [
    'class',
    'finalFocus',
    'initialFocus',
    'render',
    'children',
  ]);

  const finalFocus = () => access(local.finalFocus);

  const {
    descriptionElementId,
    dismissible,
    floatingRootContext,
    getPopupProps,
    modal,
    mounted,
    nested,
    nestedOpenDialogCount,
    setOpen,
    open,
    openMethod,
    refs,
    setPopupElement,
    titleElementId,
    transitionStatus,
    onOpenChangeComplete,
  } = useDialogRootContext();

  useOpenChangeComplete({
    open,
    ref: () => refs.popupRef,
    onComplete() {
      if (open()) {
        onOpenChangeComplete?.(true);
      }
    },
  });

  const { popupProps, resolvedInitialFocus, dialogPopupRef } = useDialogPopup({
    descriptionElementId,
    initialFocus: local.initialFocus,
    modal,
    mounted,
    setOpen,
    openMethod,
    setPopupElement,
    titleElementId,
  });

  const dialogPortalContext = useDialogPortalContext();

  const nestedDialogOpen = () => nestedOpenDialogCount() > 0;

  const state: DialogPopup.State = {
    open,
    nested,
    transitionStatus,
    nestedDialogOpen,
  };

  return (
    <>
      {mounted() && modal() === true && (
        <InternalBackdrop
          managed
          inert={inertValue(!open())}
          ref={(el) => {
            refs.internalBackdropRef = el;
          }}
        />
      )}
      <FloatingFocusManager
        context={floatingRootContext}
        disabled={!mounted()}
        closeOnFocusOut={dismissible?.()}
        initialFocus={resolvedInitialFocus()}
        returnFocus={finalFocus()}
        modal={modal() !== false}
      >
        <RenderElement
          element="div"
          componentProps={componentProps}
          ref={(el) => {
            refs.popupRef = el;
            useForkRef(componentProps.ref, dialogPopupRef)(el);
          }}
          params={{
            state,
            props: [
              getPopupProps(),
              popupProps(),
              {
                style: {
                  [DialogPopupCssVars.nestedDialogs]: nestedOpenDialogCount(),
                } as JSX.CSSProperties,
              },
              elementProps as JSX.HTMLAttributes<HTMLDivElement>,
            ],
            customStyleHookMapping,
          }}
        />
      </FloatingFocusManager>
    </>
  );
}

export namespace DialogPopup {
  export interface Props extends BaseUIComponentProps<'div', State> {
    /**
     * Determines the element to focus when the dialog is opened.
     * By default, the first focusable element is focused.
     */
    initialFocus?:
      | MaybeAccessor<HTMLElement | null | undefined>
      | ((interactionType: InteractionType) => HTMLElement | null | undefined);
    /**
     * Determines the element to focus when the dialog is closed.
     * By default, focus returns to the trigger.
     */
    finalFocus?: MaybeAccessor<HTMLElement | null | undefined>;
  }

  export interface State {
    /**
     * Whether the dialog is currently open.
     */
    open: MaybeAccessor<boolean>;
    transitionStatus: MaybeAccessor<TransitionStatus>;
    /**
     * Whether the dialog is nested within a parent dialog.
     */
    nested: MaybeAccessor<boolean>;
    /**
     * Whether the dialog has nested dialogs open.
     */
    nestedDialogOpen: MaybeAccessor<boolean>;
  }
}
