// packages/solid/src/checkbox-group/useCheckboxGroupParent.ts
'use client';
import { batch, createSignal, type Accessor } from 'solid-js';
import { useBaseUiId } from '../utils/useBaseUiId';

const EMPTY: string[] = [];

export function useCheckboxGroupParent(
  params: useCheckboxGroupParent.Parameters,
): useCheckboxGroupParent.ReturnValue {
  const allValues = () => params.allValues?.() ?? EMPTY;
  const value = () => params.value?.() ?? EMPTY;

  let uncontrolledStateRef = value();
  const disabledStatesRef = new Map<string, boolean>();

  const [status, setStatus] = createSignal<'on' | 'off' | 'mixed'>('mixed');

  const id = useBaseUiId();
  const checked = () => value().length === allValues().length;
  const indeterminate = () => value().length !== allValues().length && value().length > 0;

  const getParentProps: useCheckboxGroupParent.ReturnValue['getParentProps'] = () => ({
    get id() {
      return id();
    },
    get indeterminate() {
      return indeterminate();
    },
    get checked() {
      return checked();
    },
    get 'aria-controls'() {
      return allValues()
        .map((v) => `${id()}-${v}`)
        .join(' ');
    },
    onCheckedChange(_, event) {
      batch(() => {
        const uncontrolledState = uncontrolledStateRef;

        // None except the disabled ones that are checked, which can't be changed.
        const none = allValues().filter(
          (v) => disabledStatesRef.get(v) && uncontrolledState.includes(v),
        );
        // "All" that are valid:
        // - any that aren't disabled
        // - disabled ones that are checked
        const all = allValues().filter(
          (v) =>
            !disabledStatesRef.get(v) ||
            (disabledStatesRef.get(v) && uncontrolledState.includes(v)),
        );

        const allOnOrOff =
          uncontrolledState.length === all.length || uncontrolledState.length === 0;

        if (allOnOrOff) {
          if (value().length === all.length) {
            params.onValueChange?.(none, event);
          } else {
            params.onValueChange?.(all, event);
          }
          return;
        }

        if (status() === 'mixed') {
          params.onValueChange?.(all, event);
          setStatus('on');
        } else if (status() === 'on') {
          params.onValueChange?.(none, event);
          setStatus('off');
        } else if (status() === 'off') {
          params.onValueChange?.(uncontrolledState, event);
          setStatus('mixed');
        }
      });
    },
  });

  const getChildProps: useCheckboxGroupParent.ReturnValue['getChildProps'] = (name: string) => ({
    get name() {
      return name;
    },
    get id() {
      return `${id()}-${name}`;
    },
    get checked() {
      return value().includes(name);
    },
    onCheckedChange(nextChecked, event) {
      batch(() => {
        const newValue = value().slice();
        if (nextChecked) {
          newValue.push(name);
        } else {
          newValue.splice(newValue.indexOf(name), 1);
        }
        uncontrolledStateRef = newValue;
        params.onValueChange?.(newValue, event);
        setStatus('mixed');
      });
    },
  });

  return {
    id,
    indeterminate,
    getParentProps,
    getChildProps,
    disabledStatesRef,
  };
}

export namespace useCheckboxGroupParent {
  export interface Parameters {
    allValues?: Accessor<string[] | undefined>;
    value?: Accessor<string[] | undefined>;
    onValueChange?: (value: string[], event: Event) => void;
  }

  export interface ReturnValue {
    id: Accessor<string | undefined>;
    indeterminate: Accessor<boolean>;
    disabledStatesRef: Map<string, boolean>;
    getParentProps: () => {
      id: string | undefined;
      indeterminate: boolean;
      checked: boolean;
      'aria-controls': string;
      onCheckedChange: (checked: boolean, event: Event) => void;
    };
    getChildProps: (name: string) => {
      name: string;
      id: string;
      checked: boolean;
      onCheckedChange: (checked: boolean, event: Event) => void;
    };
  }
}

// packages/react/src/checkbox-group/useCheckboxGroupParent.ts
'use client';
import * as React from 'react';
import { useBaseUiId } from '../utils/useBaseUiId';
import { useEventCallback } from '../utils/useEventCallback';

const EMPTY: string[] = [];

export function useCheckboxGroupParent(
  params: useCheckboxGroupParent.Parameters,
): useCheckboxGroupParent.ReturnValue {
  const { allValues = EMPTY, value = EMPTY, onValueChange: onValueChangeProp } = params;

  const uncontrolledStateRef = React.useRef(value);
  const disabledStatesRef = React.useRef(new Map<string, boolean>());

  const [status, setStatus] = React.useState<'on' | 'off' | 'mixed'>('mixed');

  const id = useBaseUiId();
  const checked = value.length === allValues.length;
  const indeterminate = value.length !== allValues.length && value.length > 0;

  const onValueChange = useEventCallback(onValueChangeProp);

  const getParentProps: useCheckboxGroupParent.ReturnValue['getParentProps'] = React.useCallback(
    () => ({
      id,
      indeterminate,
      checked,
      'aria-controls': allValues.map((v) => `${id}-${v}`).join(' '),
      onCheckedChange(_, event) {
        const uncontrolledState = uncontrolledStateRef.current;
        // None except the disabled ones that are checked, which can't be changed.
        const none = allValues.filter(
          (v) => disabledStatesRef.current.get(v) && uncontrolledState.includes(v),
        );
        // "All" that are valid:
        // - any that aren't disabled
        // - disabled ones that are checked
        const all = allValues.filter(
          (v) =>
            !disabledStatesRef.current.get(v) ||
            (disabledStatesRef.current.get(v) && uncontrolledState.includes(v)),
        );

        const allOnOrOff =
          uncontrolledState.length === all.length || uncontrolledState.length === 0;

        if (allOnOrOff) {
          if (value.length === all.length) {
            onValueChange(none, event);
          } else {
            onValueChange(all, event);
          }
          return;
        }

        if (status === 'mixed') {
          onValueChange(all, event);
          setStatus('on');
        } else if (status === 'on') {
          onValueChange(none, event);
          setStatus('off');
        } else if (status === 'off') {
          onValueChange(uncontrolledState, event);
          setStatus('mixed');
        }
      },
    }),
    [allValues, checked, id, indeterminate, onValueChange, status, value.length],
  );

  const getChildProps: useCheckboxGroupParent.ReturnValue['getChildProps'] = React.useCallback(
    (name: string) => ({
      name,
      id: `${id}-${name}`,
      checked: value.includes(name),
      onCheckedChange(nextChecked, event) {
        const newValue = value.slice();
        if (nextChecked) {
          newValue.push(name);
        } else {
          newValue.splice(newValue.indexOf(name), 1);
        }
        uncontrolledStateRef.current = newValue;
        onValueChange(newValue, event);
        setStatus('mixed');
      },
    }),
    [id, onValueChange, value],
  );

  return React.useMemo(
    () => ({
      id,
      indeterminate,
      getParentProps,
      getChildProps,
      disabledStatesRef,
    }),
    [id, indeterminate, getParentProps, getChildProps],
  );
}

export namespace useCheckboxGroupParent {
  export interface Parameters {
    allValues?: string[];
    value?: string[];
    onValueChange?: (value: string[], event: Event) => void;
  }

  export interface ReturnValue {
    id: string | undefined;
    indeterminate: boolean;
    disabledStatesRef: React.MutableRefObject<Map<string, boolean>>;
    getParentProps: () => {
      id: string | undefined;
      indeterminate: boolean;
      checked: boolean;
      'aria-controls': string;
      onCheckedChange: (checked: boolean, event: Event) => void;
    };
    getChildProps: (name: string) => {
      name: string;
      id: string;
      checked: boolean;
      onCheckedChange: (checked: boolean, event: Event) => void;
    };
  }
}
